name: 下载配置文件

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 55 15 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 准备完成
      uses: actions/checkout@v4

    - name: 下载架构编译配置文件
      run: |
        wget -O ./feeds.conf https://fw0.koolcenter.com/iStoreOS/alpha/x86_64_efi/feeds.conf
        wget -O ./.config https://fw0.koolcenter.com/iStoreOS/alpha/x86_64_efi/config.buildinfo

    - name: 注释软件源
      run: |
        #注释应用过滤
        sed -i 's/^.*OpenAppFilter.*/#&/' feeds.conf
        
        #移除应用过滤
        sed -i 's/CONFIG_PACKAGE_appfilter=y/CONFIG_PACKAGE_appfilter=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-oaf=y/CONFIG_PACKAGE_kmod-oaf=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-app-oaf=y/CONFIG_PACKAGE_luci-app-oaf=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-oaf-zh-cn=y/CONFIG_PACKAGE_luci-i18n-oaf-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-oaf=y/CONFIG_PACKAGE_kmod-oaf=n/' .config
        
        #移除网络唤醒
        sed -i 's/CONFIG_PACKAGE_luci-app-wol=y/CONFIG_PACKAGE_luci-app-wol=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y/CONFIG_PACKAGE_luci-i18n-wol-zh-cn=n/' .config
        
        #移除硬盘休眠
        sed -i 's/CONFIG_PACKAGE_luci-app-hd-idle=y/CONFIG_PACKAGE_luci-app-hd-idle=n/' .config
        sed -i 's/CONFIG_PACKAGE_hd-idle=y/CONFIG_PACKAGE_hd-idle=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y/CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=n/' .config
        
        #移除samba4
        sed -i 's/CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y/CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-app-samba4=y/CONFIG_PACKAGE_luci-app-samba4=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_AVAHI=y/CONFIG_SAMBA4_SERVER_AVAHI=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_NETBIOS=y/CONFIG_SAMBA4_SERVER_NETBIOS=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_VFS=y/CONFIG_SAMBA4_SERVER_VFS=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_WSDD2=y/CONFIG_SAMBA4_SERVER_WSDD2=n/' .config
        sed -i 's/CONFIG_PACKAGE_samba4-libs=y/CONFIG_PACKAGE_samba4-libs=n/' .config
        sed -i 's/CONFIG_PACKAGE_samba4-server=y/CONFIG_PACKAGE_samba4-server=n/' .config
        
        #移除统一文件共享
        sed -i 's/CONFIG_PACKAGE_luci-app-unishare=y/CONFIG_PACKAGE_luci-app-unishare=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-unishare-zh-cn=y/CONFIG_PACKAGE_luci-i18n-unishare-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_unishare=y/CONFIG_PACKAGE_unishare=n/' .config
        
        #移除NFS
        sed -i 's/CONFIG_PACKAGE_luci-app-nfs=y/CONFIG_PACKAGE_luci-app-nfs=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-nfs-zh-cn=y/CONFIG_PACKAGE_luci-i18n-nfs-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-kernel-server=y/CONFIG_PACKAGE_nfs-kernel-server=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-kernel-server-utils=y/CONFIG_PACKAGE_nfs-kernel-server-utils=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-utils=y/CONFIG_PACKAGE_nfs-utils=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-utils-libs=y/CONFIG_PACKAGE_nfs-utils-libs=n/' .config
        sed -i 's/CONFIG_NFS_KERNEL_SERVER_V4=y/CONFIG_NFS_KERNEL_SERVER_V4=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs=y/CONFIG_PACKAGE_kmod-fs-nfs=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-common=y/CONFIG_PACKAGE_kmod-fs-nfs-common=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y/CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-v3=y/CONFIG_PACKAGE_kmod-fs-nfs-v3=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-v4=y/CONFIG_PACKAGE_kmod-fs-nfs-v4=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfsd=y/CONFIG_PACKAGE_kmod-fs-nfsd=n/' .config
        
        #移除挂载网络共享
        sed -i 's/CONFIG_PACKAGE_luci-app-cifs-mount=y/CONFIG_PACKAGE_luci-app-cifs-mount=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-cifs-mount-zh-cn=y/CONFIG_PACKAGE_luci-i18n-cifs-mount-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_cifsmount=y/CONFIG_PACKAGE_cifsmount=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-cifs=y/CONFIG_PACKAGE_kmod-fs-cifs=n/' .config

        #移除挂载网络共享
        sed -i 's/CONFIG_PACKAGE_luci-app-ota=y/CONFIG_PACKAGE_luci-app-ota=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-ota-zh-cn=y/CONFIG_PACKAGE_luci-i18n-ota-zh-cn=n/' .config
        
        # 移除 bootstrap 主题
        sed -i 's/CONFIG_PACKAGE_luci-theme-bootstrap=y/CONFIG_PACKAGE_luci-theme-bootstrap=n/' .config
        
    - name: 同步配置
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"

    - name: 删除运行记录
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.TOKEN }}
